# Generated by Django 5.2.4 on 2025-07-19 04:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id_fundo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Fundo')),
                ('st_cnpj_fundo', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato XX.XXX.XXX/XXXX-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ do Fundo')),
                ('st_classe_fundo', models.CharField(max_length=100, verbose_name='Classe ANBIMA do Fundo')),
                ('st_estrategia_fundo', models.TextField(verbose_name='Estratégia de Investimento')),
                ('st_obs_fundo', models.TextField(blank=True, null=True, verbose_name='Observações Gerais')),
                ('cod_quantum_fundomaster', models.IntegerField(blank=True, null=True, verbose_name='Código do Fundo Master')),
                ('st_cnpj_fundomaster', models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato XX.XXX.XXX/XXXX-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ do Fundo Master')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fundo',
                'verbose_name_plural': 'Fundos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FundoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='fundos.fundo')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundos.relatorio')),
            ],
            options={
                'verbose_name': 'Fundo-Relatório',
                'verbose_name_plural': 'Fundos-Relatórios',
                'unique_together': {('fundo', 'relatorio')},
            },
        ),
    ]
